name: listener-workflow
on:
  issues:
    types: [opened, edited, deleted, closed]
jobs:
  issues_listener:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue info
        run: |
          echo "${{toJson(github.event)}}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Issue State: ${{ github.event.issue.state }}"
          echo "Issue URL: ${{ github.event.issue.html_url }}"
          echo "Action: ${{ github.event.action }}"
